### ISSUE TITLE
evaluation data files in eval_gen.py

### ISSUE THREAD

**Issue by SherrySwift** [hdong920/LESS#2]
Hi, thanks for your great work!
I tried to run src/example_scripts/eval/llama2_7b/cnn_dailymail.sh, but it seems that the evaluation data files used in eval_gen.py are missing (cnn_dailymail_5shot.jsonl, xsum_5shot.jsonl, multinews_5shot_1.jsonl). Would you please provide these data files? Thanks a lot!

**Comment by hdong920** [comment]
Uploaded!
